
export const REQUEST_MOVIE_TOP250 = 'REQUEST_MOVIE_TOP250';
export const RECEIVE_MOVIE_TOP250 = 'RECEIVE_MOVIE_TOP250';

export const REQUEST_MOVIE_DETAIL = 'REQUEST_MOVIE_DETAIL';
export const RECEIVE_MOVIE_DETAIL = 'RECEIVE_MOVIE_DETAIL';

export const REQUEST_ACTOR_DETAIL = 'REQUEST_ACTOR_DETAIL';
export const RECEIVE_ACTOR_DETAIL = 'RECEIVE_ACTOR_DETAIL';